# Usage: "brew bundle"
#
# 1. Install XCode command line utilities:
#     xcode-select --install
# 2. Install Homebrew (from the site):
#     open https://brew.sh
# 3. Install packagees
#     brew bundle

brew "aws-shell"
brew "aws-sam-cli"
brew "awscli"
brew "black"
brew "checkbashisms"
brew "clisp"
brew "clojure"
brew "cowsay"
brew "dos2unix"
brew "elm"
brew "fortune"
brew "gh"
brew "ghc"
brew "git"
brew "gti"
brew "gpg"
brew "htop"
brew "iperf3"
brew "jq"
brew "jsonpp"
brew "leiningen"
# brew "monetdb"
cask "miniconda"
# x86 -- brew "mit-scheme"
brew "node@16"
brew "nvm"
brew "openjdk@11"
# brew "pgbadger"
brew "postgresql@14"
brew "python@3.11"
brew "python-tk@3.11"
cask "racket"
brew "readline"
brew "rlwrap"
brew "sbcl"
brew "sl"
brew "sqlite"
brew "wget"
brew "xonsh"
